field: e08d5489-5f32-423e-b815-1f3c915bba0a # Button
fieldLayouts:
  f98cde7c-715d-4e26-b5ba-f8a61bff4fc2:
    tabs:
      -
        elements:
          -
            fieldUid: 1c10c924-e9e5-4b46-8f43-c4a8e68735f5 # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1c10c924-e9e5-4b46-8f43-c4a8e68735f5: # Button
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: button
    instructions: ''
    name: Button
    searchable: true
    settings:
      columns:
        __assoc__:
          -
            - a8e6bff5-3c4e-47da-8bfa-f03179d9a372 # Label
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 6cee9642-f677-4f79-9027-eab0f5c64112 # Link
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 39c07810-5e4b-49a3-b885-002ae031ae1e # Color
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 2741e591-f4d3-457f-b3a1-82d24fa6a46e # Outline
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 39782143-cf87-4e23-b74e-06459a71bc84 # New Tab
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_4_button}}'
      fieldLayout: table
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: ''
      staticField: '1'
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: customLink
name: 'Custom Link'
sortOrder: 3
