field: d750001c-1757-4202-b47a-f386339aa476 # Project Buttons
fieldLayouts:
  7d62a3e2-140f-431a-bbc3-1995787979d7:
    tabs:
      -
        elements:
          -
            fieldUid: 36ef9a2c-6a81-4f29-906e-7a26dfec972d # Button Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: c5a79e1d-7309-4dbe-8ba5-8cabb588e4b8 # Custom Link
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: c6bc972f-7c71-4bca-9267-85072c79b764 # New Tab
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
        name: Content
        sortOrder: 1
fields:
  36ef9a2c-6a81-4f29-906e-7a26dfec972d: # Button Label
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: ''
    name: 'Button Label'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c5a79e1d-7309-4dbe-8ba5-8cabb588e4b8: # Custom Link
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: customLink
    instructions: 'include https:// when linking to offsite resources'
    name: 'Custom Link'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: '1'
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c6bc972f-7c71-4bca-9267-85072c79b764: # New Tab
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: newTab
    instructions: ''
    name: 'New Tab'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: customLink
name: 'Custom Link'
sortOrder: 3
