field: e08d5489-5f32-423e-b815-1f3c915bba0a # Button
fieldLayouts:
  c8b193c9-049a-4496-a567-ba6aa253f7a9:
    tabs:
      -
        elements:
          -
            fieldUid: 89254b6b-a516-4069-b20e-2290e94781c4 # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  89254b6b-a516-4069-b20e-2290e94781c4: # Button
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: button
    instructions: ''
    name: Button
    searchable: true
    settings:
      columns:
        __assoc__:
          -
            - 92cc90a8-7ba4-4638-9b02-9db86ba60e18 # Label
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 2d58dfa0-4c26-4b8d-9043-bb7d596a6348 # Link
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 343f01eb-8b9b-4be6-9f49-2364b0fa706e # Color
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - f6cd235b-8200-4194-872f-94995dd9c1f7 # Outline
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 88bcbf67-1f4c-428c-a36e-f36be8154323 # New Tab
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_3_button}}'
      fieldLayout: table
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: ''
      staticField: '1'
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: linkToAsset
name: 'Link to Asset'
sortOrder: 2
