field: e08d5489-5f32-423e-b815-1f3c915bba0a # Button
fieldLayouts:
  d0f4432a-205a-46b9-bae6-1342b679dec8:
    tabs:
      -
        elements:
          -
            fieldUid: d61c5b5f-313d-4082-91ca-5f3a165ab830 # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  d61c5b5f-313d-4082-91ca-5f3a165ab830: # Button
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: button
    instructions: ''
    name: Button
    searchable: true
    settings:
      columns:
        __assoc__:
          -
            - e3aaa9fb-8db4-4298-b072-81955f6459c5 # Label
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - b2d44570-8139-4190-afd4-1db2035be921 # Link
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - c60de8b5-0e28-4ef9-8465-fbb2f6666fd8 # Color
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 2ad91579-2e28-4ab7-9607-9b7ba99101bd # Outline
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 41df0d40-d2d8-4fcb-a04b-434a40322ffa # New Tab
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_2_button}}'
      fieldLayout: table
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: 'Add a button'
      staticField: '1'
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: linkToPage
name: 'Link to Page'
sortOrder: 1
