fieldLayouts:
  4cffffd3-66b0-4cd3-9cb8-18806285ba24:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: ace36172-34f0-4cf8-a445-bb51e06d0201 # Thumbnail
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 558734bc-5701-4caa-b772-d6378b0e9471 # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            heading: Categories
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: 4f7cfc53-0bc9-46b4-83c9-71ed2feaed7d # Industries
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 067f50e9-5df4-44e9-b2f2-9973b0841473 # Categories
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 81c31ad7-3023-456d-9403-f39b95fa76c9 # Clients
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
        name: 'Preview Card'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 20318ea5-ac91-4972-8c4e-74158975017d # Page Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e7fd2fec-63f4-45f4-8e16-be48c05290c2 # Page Body Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Detail Page'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 0aaabdbe-664b-4783-a64d-f34e68646962 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 3
handle: work
hasTitleField: true
name: Work
section: f02620c0-a7e8-4078-9914-50ec1436db7b # Work
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
