baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Heinley Projects'
primary: true
siteGroup: 98f9c9ed-636a-496e-967e-f30f6f78a90c # Heinley Projects
sortOrder: 1
