childBlocks: null
field: 20318ea5-ac91-4972-8c4e-74158975017d # Page Header
fieldLayouts:
  b15c4af2-3b5c-43fe-9486-876bf2024682:
    tabs:
      -
        elements:
          -
            fieldUid: 9a09ff48-0e98-452d-a971-4c0c69dbd409 # Images
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f9e16de3-208f-444b-9217-83a666e1e86f # Heading: Basic
            instructions: ''
            label: Heading
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 558734bc-5701-4caa-b772-d6378b0e9471 # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: carousel
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Carousel
sortOrder: 3
topLevel: true
