childBlocks: null
field: e7fd2fec-63f4-45f4-8e16-be48c05290c2 # Page Body Blocks
fieldLayouts:
  a3eb4832-1b00-4f1d-98d9-2ab2044744c8:
    tabs:
      -
        elements:
          -
            fieldUid: 5c646279-405f-4f07-a2b6-ae8c87d609e7 # Caption
            instructions: ''
            label: 'Section Pre-Heading'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: f9e16de3-208f-444b-9217-83a666e1e86f # Heading: Basic
            instructions: ''
            label: 'Section Heading'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 8151b3b3-4e02-4c29-9396-ed7ddd8915ec # Color
            instructions: ''
            label: 'Heading Color'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: ad8dce71-499e-4992-b946-89dbc49e35ff # Image
            instructions: ''
            label: Icon
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: c6899c47-98ae-40c6-89d6-20ba6e4b9dea # Image Position [L|R]
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 7523a3ff-5e73-4eeb-897f-c7b8eff35112 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 84c12fb7-8668-4f9a-a0e6-15358ff60a18 # Background Photo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 0b7f01f8-e48c-475c-ac9f-946a662edcfa # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 3e5fcd52-1f19-44d2-a8d5-d06fc1ddf8dc # Padding: Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: b0f02fc7-d7bf-452b-83f6-3d660934f29a # Padding: Bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
        name: 'Section Settings'
        sortOrder: 2
handle: iconTextBlock
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Icon+Text Block'
sortOrder: 4
topLevel: true
