childBlocks: null
field: e7fd2fec-63f4-45f4-8e16-be48c05290c2 # Page Body Blocks
fieldLayouts:
  087a4704-a3bf-4273-a92e-0f65f7d685ad:
    tabs:
      -
        elements:
          -
            fieldUid: 5c646279-405f-4f07-a2b6-ae8c87d609e7 # Caption
            instructions: ''
            label: 'Section Pre-Heading'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: f9e16de3-208f-444b-9217-83a666e1e86f # Heading: Basic
            instructions: ''
            label: 'Section Heading'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 8151b3b3-4e02-4c29-9396-ed7ddd8915ec # Color
            instructions: ''
            label: 'Heading Color'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: e43e9c45-be3d-4b2c-9622-4ba3c65d45a3 # Heading: Block
            instructions: ''
            label: Heading
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9a09ff48-0e98-452d-a971-4c0c69dbd409 # Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 84c12fb7-8668-4f9a-a0e6-15358ff60a18 # Background Photo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 0b7f01f8-e48c-475c-ac9f-946a662edcfa # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 3e5fcd52-1f19-44d2-a8d5-d06fc1ddf8dc # Padding: Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: b0f02fc7-d7bf-452b-83f6-3d660934f29a # Padding: Bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 7a3f3b69-ae91-44fa-8af4-8a7d7b75a669 # Padding: Sides
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
        name: 'Section Settings'
        sortOrder: 2
handle: imageCarousel
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Image Carousel'
sortOrder: 10
topLevel: true
