childBlocks: null
field: e7fd2fec-63f4-45f4-8e16-be48c05290c2 # Page Body Blocks
fieldLayouts:
  382bbefa-e3a0-4f16-8dd6-af38cd447706:
    tabs:
      -
        elements:
          -
            fieldUid: ad8dce71-499e-4992-b946-89dbc49e35ff # Image
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f30475bd-b8d8-4f24-9df7-e43128f03d0a # Image Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Logo
        sortOrder: 1
handle: logo
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Logo
sortOrder: 15
topLevel: false
