childBlocks:
  - logo
field: e7fd2fec-63f4-45f4-8e16-be48c05290c2 # Page Body Blocks
fieldLayouts:
  2ab54655-8fd2-49ca-aa5f-81aabe96d226:
    tabs:
      -
        elements:
          -
            fieldUid: 5c646279-405f-4f07-a2b6-ae8c87d609e7 # Caption
            instructions: ''
            label: 'Section Pre-Heading'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: f9e16de3-208f-444b-9217-83a666e1e86f # Heading: Basic
            instructions: ''
            label: 'Section Heading'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 8151b3b3-4e02-4c29-9396-ed7ddd8915ec # Color
            instructions: ''
            label: 'Heading Color'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 84c12fb7-8668-4f9a-a0e6-15358ff60a18 # Background Photo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 0b7f01f8-e48c-475c-ac9f-946a662edcfa # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 3e5fcd52-1f19-44d2-a8d5-d06fc1ddf8dc # Padding: Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: b0f02fc7-d7bf-452b-83f6-3d660934f29a # Padding: Bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 7a3f3b69-ae91-44fa-8af4-8a7d7b75a669 # Padding: Sides
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 0f7a16e9-8454-4ca2-aef3-e3043744ee82 # Items Per Row
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
        name: 'Section Settings'
        sortOrder: 2
handle: logos
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Logos
sortOrder: 14
topLevel: true
