childBlocks: null
field: 20318ea5-ac91-4972-8c4e-74158975017d # Page Header
fieldLayouts:
  f2d4b9ee-159f-48ed-a200-290620b573e9:
    tabs:
      -
        elements:
          -
            fieldUid: 84c12fb7-8668-4f9a-a0e6-15358ff60a18 # Background Photo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f9e16de3-208f-444b-9217-83a666e1e86f # Heading: Basic
            instructions: ''
            label: Heading
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 558734bc-5701-4caa-b772-d6378b0e9471 # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: photo
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Photo
sortOrder: 2
topLevel: true
