childBlocks: null
field: 20318ea5-ac91-4972-8c4e-74158975017d # Page Header
fieldLayouts:
  add11de8-f0e2-4fd3-b26f-b48d65bedf51:
    tabs:
      -
        elements:
          -
            fieldUid: 0b7f01f8-e48c-475c-ac9f-946a662edcfa # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f9e16de3-208f-444b-9217-83a666e1e86f # Heading: Basic
            instructions: ''
            label: Heading
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 558734bc-5701-4caa-b772-d6378b0e9471 # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: solidColor
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Solid Color'
sortOrder: 1
topLevel: true
