childBlocks: null
field: e7fd2fec-63f4-45f4-8e16-be48c05290c2 # Page Body Blocks
fieldLayouts:
  970c08b5-4e2a-4671-ac8a-fdc0510f6a91:
    tabs:
      -
        elements:
          -
            fieldUid: d340bc32-388f-410d-be63-775b23be2c69 # Quote
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ab1cfa5c-020c-46af-baa1-453427f2e717 # Citation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 492246bd-0682-4e55-9862-e7880b62e9ad # Text Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Testimonial
        sortOrder: 1
handle: testimonial
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Testimonial
sortOrder: 16
topLevel: false
