childBlocks: null
field: e7fd2fec-63f4-45f4-8e16-be48c05290c2 # Page Body Blocks
fieldLayouts:
  073435e7-6f52-4980-8451-4b2338fbc333:
    tabs:
      -
        elements:
          -
            fieldUid: d340bc32-388f-410d-be63-775b23be2c69 # Quote
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ab1cfa5c-020c-46af-baa1-453427f2e717 # Citation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: testimonial
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Testimonial
sortOrder: 13
topLevel: false
