columnSuffix: lxnjtxdu
contentColumnType: text
fieldGroup: 5e594575-1d3b-4fd7-92e1-13f3e1fc2856 # Text Fields
handle: cityState
instructions: 'Austin, TX'
name: 'City, State'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: 1
  columnType: text
  initialRows: 4
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
