columnSuffix: cgmburpd
contentColumnType: string
fieldGroup: 5e594575-1d3b-4fd7-92e1-13f3e1fc2856 # Text Fields
handle: email
instructions: ''
name: Email
searchable: true
settings:
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
