columnSuffix: null
contentColumnType: string
fieldGroup: 937fbfdd-6234-4c28-ada8-7effcfefb0b0 # Matrix Fields
handle: figure
instructions: ''
name: Figure
searchable: true
settings:
  columns:
    __assoc__:
      -
        - fea64eec-cc78-43c2-9a09-476834e5281d # Image
        -
          __assoc__:
            -
              - width
              - ''
      -
        - a3a4f256-a876-418b-8dc0-f3bd6ba40e18 # Position
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_figure}}'
  fieldLayout: table
  maxRows: '1'
  minRows: ''
  placeholderKey: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: 'Add a figure'
  staticField: ''
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
