columnSuffix: fixsuytk
contentColumnType: string
fieldGroup: e3f6200d-59f1-4ccd-8047-5a643809c5b8 # Select Fields
handle: itemsPerRow
instructions: ''
name: 'Items Per Row'
searchable: true
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - '2'
        -
          - value
          - '2'
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - '3'
        -
          - value
          - '3'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '4'
        -
          - value
          - '4'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '6'
        -
          - value
          - '6'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
