columnSuffix: null
contentColumnType: string
fieldGroup: 995636a1-0afe-4190-bfc1-25fd9ab86bc0 # Element Fields
handle: pages
instructions: ''
name: Pages
searchable: true
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: null
  sources:
    - 'section:fcb4743e-980b-45d7-9fb3-40320d59f94b'
  targetSiteId: null
  validateRelatedElements: true
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
