columnSuffix: null
contentColumnType: string
fieldGroup: 937fbfdd-6234-4c28-ada8-7effcfefb0b0 # Matrix Fields
handle: projectButtons
instructions: ''
name: 'Project Buttons'
searchable: false
settings:
  contentTable: '{{%matrixcontent_projectbuttons}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
