columnSuffix: null
contentColumnType: string
fieldGroup: 937fbfdd-6234-4c28-ada8-7effcfefb0b0 # Matrix Fields
handle: textLink
instructions: ''
name: 'Text Link'
searchable: true
settings:
  contentTable: '{{%stc_textlink}}'
  fieldLayout: table
  maxRows: '1'
  minRows: ''
  placeholderKey: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: 'Add a link'
  staticField: ''
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
