columnSuffix: owfgjduy
contentColumnType: string(255)
fieldGroup: 5e594575-1d3b-4fd7-92e1-13f3e1fc2856 # Text Fields
handle: website
instructions: 'include https:// when linking to offsite resources'
name: Website
searchable: true
settings:
  maxLength: '255'
  placeholder: null
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
