field: e43e9c45-be3d-4b2c-9622-4ba3c65d45a3 # Heading: Block
fieldLayouts:
  32be4299-d4e8-40f1-8e5b-63a308092c00:
    tabs:
      -
        elements:
          -
            fieldUid: 970b3f86-5751-4ca9-b7d5-cad668aec67c # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9f577edf-34a4-44e1-8c7d-9da21df51b7b # Size
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2fdd083b-a83d-42d3-9f82-86b8142d25e0 # Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 941b5b11-3500-4788-9e93-6831a0a53fe0 # Alignment
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2fdd083b-a83d-42d3-9f82-86b8142d25e0: # Color
    columnSuffix: kjmoyusv
    contentColumnType: string
    fieldGroup: null
    handle: color
    instructions: ''
    name: Color
    searchable: true
    settings:
      dataSet: 'CSS Color Classes'
      type: dropdown
    translationKeyFormat: null
    translationMethod: site
    type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
  9f577edf-34a4-44e1-8c7d-9da21df51b7b: # Size
    columnSuffix: jpozrlvn
    contentColumnType: string
    fieldGroup: null
    handle: size
    instructions: ''
    name: Size
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 'H1 (Largest)'
            -
              - value
              - h1
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'H2 (Large)'
            -
              - value
              - h2
            -
              - default
              - 1
        -
          __assoc__:
            -
              - label
              - 'H3 (Medium)'
            -
              - value
              - h3
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'H4 (Small)'
            -
              - value
              - h4
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'H5 (Smallest)'
            -
              - value
              - h5
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Dropdown
  941b5b11-3500-4788-9e93-6831a0a53fe0: # Alignment
    columnSuffix: qkxalxcx
    contentColumnType: string
    fieldGroup: null
    handle: alignment
    instructions: ''
    name: Alignment
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - left
            -
              - default
              - 1
        -
          __assoc__:
            -
              - label
              - Center
            -
              - value
              - center
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Right
            -
              - value
              - right
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Dropdown
  970b3f86-5751-4ca9-b7d5-cad668aec67c: # Heading
    columnSuffix: arqzflso
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: 4
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
