field: f30475bd-b8d8-4f24-9df7-e43128f03d0a # Image Link
fieldLayouts:
  96258347-d8e0-4d99-9b06-8019a47c7adb:
    tabs:
      -
        elements:
          -
            fieldUid: 2df7b0e9-5ba9-4c73-9c31-438603592040 # Page
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 24e8198b-0847-4223-927f-670c875194cc # Asset
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7826679d-7421-470b-b72a-df131474b0b3 # Custom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e75f1d26-5381-4184-bb97-518b364f962d # New Tab
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2df7b0e9-5ba9-4c73-9c31-438603592040: # Page
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: linkToPage
    instructions: ''
    name: Page
    searchable: true
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  24e8198b-0847-4223-927f-670c875194cc: # Asset
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: linkToAsset
    instructions: ''
    name: Asset
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: false
      allowedKinds: null
      defaultUploadLocationSource: 'volume:14f6eefd-8aba-4860-a4c6-f1b3265c5393' # Documents
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: true
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:6a8678fb-3c02-4db5-a390-1b01c515f50e' # Photos
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:14f6eefd-8aba-4860-a4c6-f1b3265c5393' # Documents
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  7826679d-7421-470b-b72a-df131474b0b3: # Custom
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: customLink
    instructions: 'include https:// when linking to offsite resources'
    name: Custom
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: '1'
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e75f1d26-5381-4184-bb97-518b364f962d: # New Tab
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: newTab
    instructions: ''
    name: 'New Tab'
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
