field: d61c5b5f-313d-4082-91ca-5f3a165ab830 # Button
fieldLayouts:
  8cff6cdb-622e-4797-84dd-301288ac5e7a:
    tabs:
      -
        elements:
          -
            fieldUid: c57b33f1-e776-4977-8fd6-5d4d8e417c52 # Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c38fac81-ec4d-416d-85dc-4b7403d64317 # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2204286d-2556-42ce-94aa-db60b51980fe # Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f7ce14c4-f536-4997-b2eb-178f0e61f930 # Outline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e44366d1-73ec-4842-b258-2cebe7cd92e4 # New Tab
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2204286d-2556-42ce-94aa-db60b51980fe: # Color
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: color
    instructions: ''
    name: Color
    searchable: true
    settings:
      dataSet: 'CSS Color Classes'
      type: dropdown
    translationKeyFormat: null
    translationMethod: none
    type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
  c38fac81-ec4d-416d-85dc-4b7403d64317: # Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: btnLink
    instructions: ''
    name: Link
    searchable: true
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  c57b33f1-e776-4977-8fd6-5d4d8e417c52: # Label
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: ''
    name: Label
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e44366d1-73ec-4842-b258-2cebe7cd92e4: # New Tab
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: newTab
    instructions: 'open link in new tab'
    name: 'New Tab'
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  f7ce14c4-f536-4997-b2eb-178f0e61f930: # Outline
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: outline
    instructions: ''
    name: Outline
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
