field: f30475bd-b8d8-4f24-9df7-e43128f03d0a # Image Link
fieldLayouts:
  c5f5f443-e774-4da6-b829-9dcaecb53755:
    tabs:
      -
        elements:
          -
            fieldUid: c83d0b79-f0a6-4a6f-9a9f-176c1c88e0cc # Page
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 95809d3f-350a-4cf7-b822-4647c05a41fe # Asset
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c7bb0042-6505-48fc-aa5d-4243b06db4ec # Custom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f998514c-fedb-4c6b-9bbb-a68225497a5a # New Tab
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  95809d3f-350a-4cf7-b822-4647c05a41fe: # Asset
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: linkToAsset
    instructions: ''
    name: Asset
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: false
      allowedKinds: null
      defaultUploadLocationSource: 'volume:6a8678fb-3c02-4db5-a390-1b01c515f50e' # Photos
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: true
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:6a8678fb-3c02-4db5-a390-1b01c515f50e' # Photos
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  c7bb0042-6505-48fc-aa5d-4243b06db4ec: # Custom
    columnSuffix: hebdygbe
    contentColumnType: text
    fieldGroup: null
    handle: customLink
    instructions: 'include https:// when linking to offsite resources'
    name: Custom
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: '1'
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c83d0b79-f0a6-4a6f-9a9f-176c1c88e0cc: # Page
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: linkToPage
    instructions: ''
    name: Page
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  f998514c-fedb-4c6b-9bbb-a68225497a5a: # New Tab
    columnSuffix: lyhwlxkm
    contentColumnType: boolean
    fieldGroup: null
    handle: newTab
    instructions: ''
    name: 'New Tab'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
