field: f5e48ed9-4aea-438c-921e-22bd14eee501 # Text Link
fieldLayouts:
  d7124075-f6b7-42ba-bb59-bb046d02d3f2:
    tabs:
      -
        elements:
          -
            fieldUid: fa162359-552c-47e7-b170-443cf3024eb9 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b0c7b2e0-cbbd-49d8-90bf-d4e0f630a896 # Link to Page
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0bc2b531-490e-40e4-832a-3ffffe154c9c # Link to Asset
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4a9e494b-69c3-4cf4-b01f-d7f366de3eb6 # Custom Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 879ae77f-bee8-4c0b-862b-4202d644bce8 # New Tab
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0bc2b531-490e-40e4-832a-3ffffe154c9c: # Link to Asset
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: linkToAsset
    instructions: ''
    name: 'Link to Asset'
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - compressed
        - excel
        - pdf
        - powerpoint
        - text
        - word
      defaultUploadLocationSource: 'volume:4e88587f-5554-43da-a345-fd052ea87580'
      defaultUploadLocationSubpath: ''
      limit: 1
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: true
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:8d4ad930-aacf-4e13-ae97-2a7da38b9e13'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  4a9e494b-69c3-4cf4-b01f-d7f366de3eb6: # Custom Link
    columnSuffix: utygoetx
    contentColumnType: text
    fieldGroup: null
    handle: customLink
    instructions: 'include https:// when linking to offsite resources'
    name: 'Custom Link'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: 1
      columnType: text
      initialRows: 4
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  879ae77f-bee8-4c0b-862b-4202d644bce8: # New Tab
    columnSuffix: suujdmjt
    contentColumnType: boolean
    fieldGroup: null
    handle: newTab
    instructions: 'open link in a new browser tab?'
    name: 'New Tab'
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Lightswitch
  b0c7b2e0-cbbd-49d8-90bf-d4e0f630a896: # Link to Page
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: linkToPage
    instructions: ''
    name: 'Link to Page'
    searchable: true
    settings:
      allowSelfRelations: false
      limit: ''
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  fa162359-552c-47e7-b170-443cf3024eb9: # Text
    columnSuffix: shypupko
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: 4
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
