field: 1c10c924-e9e5-4b46-8f43-c4a8e68735f5 # Button
fieldLayouts:
  5dd8ec49-d23d-4541-85ed-0e40d3bb42c9:
    tabs:
      -
        elements:
          -
            fieldUid: a8e6bff5-3c4e-47da-8bfa-f03179d9a372 # Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6cee9642-f677-4f79-9027-eab0f5c64112 # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 39c07810-5e4b-49a3-b885-002ae031ae1e # Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2741e591-f4d3-457f-b3a1-82d24fa6a46e # Outline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 39782143-cf87-4e23-b74e-06459a71bc84 # New Tab
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6cee9642-f677-4f79-9027-eab0f5c64112: # Link
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: btnLink
    instructions: 'include https:// when linking to offsite resources'
    name: Link
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: '1'
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  39c07810-5e4b-49a3-b885-002ae031ae1e: # Color
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: color
    instructions: ''
    name: Color
    searchable: false
    settings:
      dataSet: 'CSS Color Classes'
      type: dropdown
    translationKeyFormat: null
    translationMethod: none
    type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
  2741e591-f4d3-457f-b3a1-82d24fa6a46e: # Outline
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: outline
    instructions: ''
    name: Outline
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  39782143-cf87-4e23-b74e-06459a71bc84: # New Tab
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: newTab
    instructions: ''
    name: 'New Tab'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  a8e6bff5-3c4e-47da-8bfa-f03179d9a372: # Label
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: ''
    name: Label
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
