defaultPlacement: end
enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  896591ef-db97-4720-a7b1-bfca1bfcd395: # M Group Agency
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: __home__
type: single
