defaultPlacement: end
enableVersioning: true
handle: pages
name: Pages
propagationMethod: all
siteSettings:
  896591ef-db97-4720-a7b1-bfca1bfcd395: # M Group Agency
    enabledByDefault: true
    hasUrls: true
    template: _pages/page.html
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 2ca56c8c-2fca-4298-b2c6-f02404c5a25c
type: structure
